# Generated by Django 3.2.8 on 2022-08-09 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='UsersBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('social_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('social_github', models.CharField(blank=True, max_length=200, null=True)),
                ('social_website', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('information_public', models.BooleanField(default=True)),
                ('notification', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('animes_done', models.ManyToManyField(blank=True, related_name='done', to='pages.Anime')),
                ('animes_dont', models.ManyToManyField(blank=True, related_name='dont', to='pages.Anime')),
                ('animes_fav', models.ManyToManyField(blank=True, related_name='fav', to='pages.Anime')),
                ('animes_later', models.ManyToManyField(blank=True, related_name='later', to='pages.Anime')),
                ('animes_now', models.ManyToManyField(blank=True, related_name='now', to='pages.Anime')),
                ('animes_want', models.ManyToManyField(blank=True, related_name='want', to='pages.Anime')),
                ('last_animes', models.ManyToManyField(blank=True, related_name='last', to='pages.Anime')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('work', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ipAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('eps_show', models.ManyToManyField(blank=True, related_name='eps_show', to='pages.Episodes')),
                ('user_ip', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
