# Generated by Django 3.2.8 on 2022-08-09 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('story', models.TextField(default='')),
                ('image_anime', models.ImageField(default='', upload_to='photos/anime')),
                ('number_episodes', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='AnimeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
        migrations.CreateModel(
            name='AnimeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnimeDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
        migrations.CreateModel(
            name='AnimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.CharField(max_length=30)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.anime')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.episodes')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.episodes')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_class',
            field=models.ManyToManyField(to='pages.AnimeClass'),
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.animedate'),
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_days',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.animedays'),
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.animestate'),
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.animetype'),
        ),
    ]
